server:
  port: 8000
  http2:
    # 启用 HTTP/2 支持，提升传输效率
    enabled: true
  compression:
    # 启用 GZIP 压缩，减少传输数据量
    enabled: true
    # 需要压缩的 MIME 类型
    mime-types: text/html, text/xml, text/plain, application/json
    # 最小压缩响应大小（字节）

spring:
  freemarker:
    check-template-location: false
  profiles:
    # 激活的环境，如果需要 quartz 分布式支持，需要修改 active: dev,quartz
    active: dev
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /自行指定位置/eladmin.pid

  #配置 Jpa
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#邮箱验证码有效时间/秒
code:
  expiration: 300

#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDIyuCsjpwBhbhoWGUMOODu0drjdsoPNnrPYD5b3/ivDuI0nZ6mIubgp3xuRuV4mSztv0Qkvu88P7mDSehsthvkVViK+9BluXNGtbbJH1JXo4rtYNYeNjuqurv8DSsWDFUVLlJe8nl4e1/30VVeeQmwN2GufOFCzfGHOCk9Xl2/cUF1I7997uoAN4b+WEtjMmMiOeI+UumhYm2CEE3vg71As9X7ZieL31W7YAao9xBDVtH7CHIV0Ax5cpVrN8stfZcyTqBqk1+UzfC1YAiSwf6d2wOOZqDy+pw5nSu/9+X//cuRzkj0m4AQ659SCsudkxqSoIBSpx58jdg8VJVHHI73AgMBAAECggEBAJqZenviIcQaTW4qAUNz19yJv9s7b0BfVhetptXekP9YmlqgsbKBVPrMekX+WFiOt8UmazVPvavJ9PBdS5PIc5lPDSmV0VNBgryC1QXuE9xek21KDhKc9zvxIyRijzYesLPqQonQcC6P78hDaVOgJhGD0rYieN6S6tCOMVKLAeuPzwbS+aH/2Zq3V7KOJwclF+XuR0+9CVxybLrOOWIWIJ3Z3ir3xX+TXIO6POf7fyETPWLbrJJEPIRERpCI8UA4v18V8OcZOCYuQ/38oz1PGs+wEjhAA8GKcnJJrLUzqWzpoD68AtTfYU2Cr8fuUclAykGf7IfNzo5Vpid6kWwnAEECgYEA5hGO31iKLhEzVV8kFIcrOxOOQvuAxYA0mQG2x69e7hASsZMPghhdCGRef2woEZUct2x+eS/x76lKm9SnbmVQvWMV6nwtUpdxIGPbvtbEtDOQlHRYzhJlARVkB2b1oCNTWkBxg8yffiHqHQdBQH4UQW61DQNbeDQvIxv72YFUej8CgYEA32yU5L9pgUsVEMxJSn8ve+85m6ir0mFy8W7xf/+ndtVBpE/gDMSJKSlaNO/atWYIG91+q/n5ZJaE52a2/eej1R9fl7rC/3UFGFaL2eiKpzj71A8vjRnceGVIbY0j93yAKnOoIas68kM+UkkC19BHFa7q89QfpEXfchy14AsPjUkCgYBsWTh/1qK8rz0Np5DGWiHx4HPO98LdQFOE+1mpEN4UH12uYyOakP6/RQV73OPB5AdyGpY1XG8D/yYz3SI8y1oK1u8rTu/JRajxKBYE+gAJHX+pamGoKuGGcRx6n/JtSDWo+1B6UZOLQ02N/iyswrOnXQvG5R3erjTExBkHhfDS4QKBgQC6U3RsvFEBmZss0iGBNkZkZiI19Vmt7sUMIgjXRV7klH7UyCRCoZj9sdXf9fQAeeHjUznztFnPEFQwIxIS955C+5IeGIvMvUuNe4fQJ8WSJcymki+Gzf12jojzi9Rl7fd479FUmtdi+L89olPzpWfS5nhc9heZSQhKwzTObor+uQKBgQDVAiKbJVMt4/HlVlvNlK5CXek/hG8ewvPuuSCXgaupEyRj+Tr2O4pXDCvAhjTt/c5YrPNMmJDaQ+1asMsuX9GyDFGW6PNuuMyYFnJFDKK+3YpTVAI1EaoCf9mRXDmuRzcqISyjFZBsOFQMVG9bJwVVvnNr1VyyppyyKuN3azOGSQ==
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyMrgrI6cAYW4aFhlDDjg7tHa43bKDzZ6z2A+W9/4rw7iNJ2epiLm4Kd8bkbleJks7b9EJL7vPD+5g0nobLYb5FVYivvQZblzRrW2yR9SV6OK7WDWHjY7qrq7/A0rFgxVFS5SXvJ5eHtf99FVXnkJsDdhrnzhQs3xhzgpPV5dv3FBdSO/fe7qADeG/lhLYzJjIjniPlLpoWJtghBN74O9QLPV+2Yni99Vu2AGqPcQQ1bR+whyFdAMeXKVazfLLX2XMk6gapNflM3wtWAIksH+ndsDjmag8vqcOZ0rv/fl//3Lkc5I9JuAEOufUgrLnZMakqCAUqcefI3YPFSVRxyO9wIDAQAB